# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MFMSrtkRvy7HZwkAwm-alCGpphaGlUki
"""

import matplotlib.pyplot as plt
import numpy as np

# Demander à l'utilisateur d'entrer le rayon
rayon = float(input("Veuillez entrer le rayon du cercle : "))

# Créer une figure et un axe
fig, ax = plt.subplots()

# Créer des données pour le cercle
theta = np.linspace(0, 2 * np.pi, 100)  # Angles de 0 à 2π
x = rayon * np.cos(theta)  # Coordonnées x
y = rayon * np.sin(theta)  # Coordonnées y

# Tracer le cercle
ax.plot(x, y, label=f'Cercle de rayon {rayon}', color='blue')

# Définir les limites de l'axe
ax.set_xlim(-rayon - 1, rayon + 1)
ax.set_ylim(-rayon - 1, rayon + 1)
ax.set_aspect('equal', 'box')  # Assurer que le cercle soit dessiné correctement

# Ajouter des étiquettes et une légende
ax.set_title('Cercle Tracé avec Matplotlib')
ax.set_xlabel('Axe X')
ax.set_ylabel('Axe Y')
ax.axhline(0, color='black',linewidth=0.5, ls='--')  # Ligne horizontale
ax.axvline(0, color='black',linewidth=0.5, ls='--')  # Ligne verticale
ax.grid(color = 'gray', linestyle = '--', linewidth = 0.5)  # Grille
ax.legend()

# Afficher le cercle
plt.show()